/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type NavigationItem = {
  _type: "navigationItem";
  title?: string;
  linkType?: "page" | "events" | "posts" | "trainers" | "vacancies" | "documents" | "custom" | "submenu";
  page?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  };
  customUrl?: string;
  children?: Array<{
    _key: string;
  } & NavigationItem>;
};

export type DonationItem = {
  _id: string;
  _type: "donationItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  programme?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "programme";
  };
  amount?: number;
  oneOffLink?: string;
  recurringLink?: string;
  order?: number;
};

export type CoreDocument = {
  _id: string;
  _type: "coreDocument";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  file?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
  order?: number;
};

export type Trainer = {
  _id: string;
  _type: "trainer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  person?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "person";
  };
  displayAsTrainer?: boolean;
  email?: string;
  expertises?: Array<string>;
  languages?: Array<"en" | "fr" | "es" | "de" | "nl" | "it" | "pt" | "ru" | "ar" | "zh" | "ja">;
};

export type Role = {
  _id: string;
  _type: "role";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  type?: "bureau-member" | "ombudsperson" | "advisory-council" | "regional-representative" | "office" | "individual-member" | "honorary-member";
  bureauRole?: "president" | "secretary-general" | "treasurer" | "vice-president";
  officeRole?: "executive-director" | "intern" | "project-manager";
  organization?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "regionalNetwork";
  };
  person?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "person";
  };
  title?: string;
  email?: string;
  start?: string;
  end?: string;
};

export type RegionalNetwork = {
  _id: string;
  _type: "regionalNetwork";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  fullName?: string;
  memberId?: string;
  region?: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  website?: string;
  wiki?: string;
  fb?: string;
  twitter?: string;
  ig?: string;
};

export type Partner = {
  _id: string;
  _type: "partner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  biography?: Array<{
    _key: string;
  } & InternationalizedArrayStringValue>;
  description?: Array<{
    _key: string;
  } & InternationalizedArrayStringValue>;
  displayAsPartner?: boolean;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Configuration = {
  _id: string;
  _type: "configuration";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  navigation?: Array<{
    _key: string;
  } & NavigationItem>;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    metadataBase?: string;
    _type: "image";
  };
  announcementBanner?: {
    enabled?: boolean;
    text?: string;
    cta?: string;
    href?: string;
  };
  footer?: {
    fineprint?: string;
    columns?: Array<{
      title?: string;
      links?: Array<{
        title?: string;
        linkType?: "page" | "events" | "posts" | "trainers" | "vacancies" | "custom";
        page?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "page";
        };
        customUrl?: string;
        _type: "footerLink";
        _key: string;
      }>;
      _type: "footerColumn";
      _key: string;
    }>;
    socialLinks?: Array<{
      platform?: "x" | "instagram" | "facebook";
      url?: string;
      _type: "socialLink";
      _key: string;
    }>;
  };
};

export type InternationalizedArrayStringValue = {
  _type: "internationalizedArrayStringValue";
  value?: string;
};

export type InternationalizedArrayString = Array<{
  _key: string;
} & InternationalizedArrayStringValue>;

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: Array<{
    _key: string;
  } & InternationalizedArrayReferenceValue>;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "post";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "event";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "programmePage";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "vacancy";
  };
};

export type Vacancy = {
  _id: string;
  _type: "vacancy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  title?: string;
  slug?: Slug;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  location?: string;
  applicationUrl?: string;
  deadline?: string;
};

export type ProgrammePage = {
  _id: string;
  _type: "programmePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  programme?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "programme";
  };
  slug?: Slug;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  language?: string;
  type?: "members" | "partners" | "programmes" | "people" | "trainers" | "vacancies" | "documents" | "other";
  slug?: Slug;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  createdAt?: string;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  contactPerson?: {
    person?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "person";
    };
    email?: string;
  };
  type?: "ga" | "seminar" | "workshop";
  slug?: Slug;
  location?: string;
  start?: string;
  end?: string;
  language?: string;
  programme?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "programme";
  };
  members?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "memberOrganisation";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "regionalNetwork";
  }>;
  partners?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "partner";
  }>;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  trainers?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "trainer";
  }>;
  registrationLink?: string;
  registrationDeadline?: string;
  attachments?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    title?: string;
    _type: "file";
    _key: string;
  }>;
};

export type Programme = {
  _id: string;
  _type: "programme";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  managers?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "person";
  }>;
  email?: string;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  language?: string;
  type?: "statement" | "press-release" | "bureau-update";
  slug?: Slug;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  date?: string;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "person";
  };
  attachments?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    title?: string;
    _type: "file";
    _key: string;
  }>;
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  biography?: InternationalizedArrayString;
  picture?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  organization?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "memberOrganisation";
  };
};

export type MemberOrganisation = {
  _id: string;
  _type: "memberOrganisation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  memberId?: string;
  country?: string;
  countryName?: string;
  membershipType?: "full" | "associate" | "observer";
  primaryRegion?: "Western Europe" | "Eastern Europe" | "Africa" | "Asia-Pacific" | "Latin America" | "MENA" | "North America and Israel" | "Caucasus";
  secondaryRegion?: "Western Europe" | "Eastern Europe" | "Africa" | "Asia-Pacific" | "Latin America" | "MENA" | "North America and Israel" | "Caucasus";
  votes?: number;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  website?: string;
  wiki?: string;
  fb?: string;
  twitter?: string;
  ig?: string;
};

export type InternationalizedArrayReference = Array<{
  _key: string;
} & InternationalizedArrayReferenceValue>;

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = NavigationItem | DonationItem | CoreDocument | Trainer | Role | RegionalNetwork | Partner | Configuration | InternationalizedArrayStringValue | InternationalizedArrayString | TranslationMetadata | InternationalizedArrayReferenceValue | Vacancy | ProgrammePage | Page | Event | Programme | Post | Person | MemberOrganisation | InternationalizedArrayReference | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "configuration" && language == $language][0] {    ...,    navigation[] {      title,      linkType,      page-> {        slug,        type      },      customUrl,      children[] {        title,        linkType,        page-> {          slug,          type        },        customUrl,        children[] {          title,          linkType,          page-> {            slug,            type          },          customUrl,          children[] {            title,            linkType,            page-> {              slug,              type            },            customUrl          }        }      }    },    announcementBanner {      enabled,      text,      cta,      href    },    footer {      fineprint,      columns[] {        title,        links[] {          title,          linkType,          page-> {            slug,            type          },          customUrl        }      },      socialLinks[] {        platform,        url      }    }  }
export type SettingsQueryResult = {
  _id: string;
  _type: "configuration";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  navigation: Array<{
    title: string | null;
    linkType: "custom" | "documents" | "events" | "page" | "posts" | "submenu" | "trainers" | "vacancies" | null;
    page: {
      slug: Slug | null;
      type: "documents" | "members" | "other" | "partners" | "people" | "programmes" | "trainers" | "vacancies" | null;
    } | null;
    customUrl: string | null;
    children: Array<{
      title: string | null;
      linkType: "custom" | "documents" | "events" | "page" | "posts" | "submenu" | "trainers" | "vacancies" | null;
      page: {
        slug: Slug | null;
        type: "documents" | "members" | "other" | "partners" | "people" | "programmes" | "trainers" | "vacancies" | null;
      } | null;
      customUrl: string | null;
      children: Array<{
        title: string | null;
        linkType: "custom" | "documents" | "events" | "page" | "posts" | "submenu" | "trainers" | "vacancies" | null;
        page: {
          slug: Slug | null;
          type: "documents" | "members" | "other" | "partners" | "people" | "programmes" | "trainers" | "vacancies" | null;
        } | null;
        customUrl: string | null;
        children: Array<{
          title: string | null;
          linkType: "custom" | "documents" | "events" | "page" | "posts" | "submenu" | "trainers" | "vacancies" | null;
          page: {
            slug: Slug | null;
            type: "documents" | "members" | "other" | "partners" | "people" | "programmes" | "trainers" | "vacancies" | null;
          } | null;
          customUrl: string | null;
        }> | null;
      }> | null;
    }> | null;
  }> | null;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    metadataBase?: string;
    _type: "image";
  };
  announcementBanner: {
    enabled: boolean | null;
    text: string | null;
    cta: string | null;
    href: string | null;
  } | null;
  footer: {
    fineprint: string | null;
    columns: Array<{
      title: string | null;
      links: Array<{
        title: string | null;
        linkType: "custom" | "events" | "page" | "posts" | "trainers" | "vacancies" | null;
        page: {
          slug: Slug | null;
          type: "documents" | "members" | "other" | "partners" | "people" | "programmes" | "trainers" | "vacancies" | null;
        } | null;
        customUrl: string | null;
      }> | null;
    }> | null;
    socialLinks: Array<{
      platform: "facebook" | "instagram" | "x" | null;
      url: string | null;
    }> | null;
  } | null;
} | null;
// Variable: featuredPostsQuery
// Query: *[_type == "post" && defined(slug.current) && language == $language] | order(date desc, _updatedAt desc) [0...$quantity] {    content,      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  type,  image,  "date": coalesce(date, _updatedAt),  "author": author->{"name": coalesce(name, "Anonymous"), picture},  "attachments": attachments[]{ "title": coalesce(title, "Document"), "url": asset->url },  }
export type FeaturedPostsQueryResult = Array<{
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  _id: string;
  status: "draft" | "published";
  title: string | "Untitled";
  slug: string | null;
  type: "bureau-update" | "press-release" | "statement" | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  date: string;
  author: {
    name: string | "Anonymous";
    picture: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  attachments: Array<{
    title: string | "Document";
    url: string | null;
  }> | null;
}>;
// Variable: postsQuery
// Query: *[_type == "post" && defined(slug.current) && language == $language && ($type == "" || type == $type)] | order(date desc, _updatedAt desc) [$offset...$limit] {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  type,  image,  "date": coalesce(date, _updatedAt),  "author": author->{"name": coalesce(name, "Anonymous"), picture},  "attachments": attachments[]{ "title": coalesce(title, "Document"), "url": asset->url },  }
export type PostsQueryResult = Array<{
  _id: string;
  status: "draft" | "published";
  title: string | "Untitled";
  slug: string | null;
  type: "bureau-update" | "press-release" | "statement" | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  date: string;
  author: {
    name: string | "Anonymous";
    picture: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  attachments: Array<{
    title: string | "Document";
    url: string | null;
  }> | null;
}>;
// Variable: postsCountQuery
// Query: count(*[_type == "post" && defined(slug.current) && language == $language && ($type == "" || type == $type)])
export type PostsCountQueryResult = number;
// Variable: moreStoriesQuery
// Query: *[_type == "post" && _id != $skip && defined(slug.current) && language == $language] | order(date desc, _updatedAt desc) [0...$limit] {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  type,  image,  "date": coalesce(date, _updatedAt),  "author": author->{"name": coalesce(name, "Anonymous"), picture},  "attachments": attachments[]{ "title": coalesce(title, "Document"), "url": asset->url },  }
export type MoreStoriesQueryResult = Array<{
  _id: string;
  status: "draft" | "published";
  title: string | "Untitled";
  slug: string | null;
  type: "bureau-update" | "press-release" | "statement" | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  date: string;
  author: {
    name: string | "Anonymous";
    picture: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  attachments: Array<{
    title: string | "Document";
    url: string | null;
  }> | null;
}>;
// Variable: postQuery
// Query: *[_type == "post" && slug.current == $slug && language == $language] [0] {    content,      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  type,  image,  "date": coalesce(date, _updatedAt),  "author": author->{"name": coalesce(name, "Anonymous"), picture},  "attachments": attachments[]{ "title": coalesce(title, "Document"), "url": asset->url },  }
export type PostQueryResult = {
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  _id: string;
  status: "draft" | "published";
  title: string | "Untitled";
  slug: string | null;
  type: "bureau-update" | "press-release" | "statement" | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  date: string;
  author: {
    name: string | "Anonymous";
    picture: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  attachments: Array<{
    title: string | "Document";
    url: string | null;
  }> | null;
} | null;
// Variable: pageQuery
// Query: *[_type == "page" && slug.current == $slug && language == $language] [0] {    _id,    content,    "title": coalesce(title, "Untitled"),    "slug": slug.current,  }
export type PageQueryResult = {
  _id: string;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  title: string | "Untitled";
  slug: string | null;
} | null;
// Variable: pageTypeQuery
// Query: *[_type == "page" && type == $type && language == $language] [0] {    _id,    content,    "title": coalesce(title, "Untitled"),  }
export type PageTypeQueryResult = {
  _id: string;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  title: string | "Untitled";
} | null;
// Variable: partnersQuery
// Query: *[_type == "partner" && displayAsPartner == true] {    _id,    "title": coalesce(title, "Untitled"),    "logo": logo.asset->url,    description  }
export type PartnersQueryResult = Array<{
  _id: string;
  title: string | "Untitled";
  logo: string | null;
  description: Array<{
    _key: string;
  } & InternationalizedArrayStringValue> | null;
}>;
// Variable: donationItemsQuery
// Query: *[_type == "donationItem"] | order(order asc) {    _id,    "title": coalesce(title, "Untitled"),    description,    "imageUrl": image.asset->url,    "programme": programme->{ _id, name },    amount,    oneOffLink,    recurringLink  }
export type DonationItemsQueryResult = Array<{
  _id: string;
  title: string | "Untitled";
  description: string | null;
  imageUrl: string | null;
  programme: {
    _id: string;
    name: null;
  } | null;
  amount: number | null;
  oneOffLink: string | null;
  recurringLink: string | null;
}>;
// Variable: coreDocumentsQuery
// Query: *[_type == "coreDocument"] | order(order asc) {    _id,    "title": coalesce(title, "Untitled"),    description,    "fileUrl": file.asset->url  }
export type CoreDocumentsQueryResult = Array<{
  _id: string;
  title: string | "Untitled";
  description: string | null;
  fileUrl: string | null;
}>;
// Variable: programmesQuery
// Query: *[_type == "programme"] {    _id,    email,    "title": coalesce(title, "Untitled"),    "managers": managers[]->{      _id,      "name": coalesce(name, "Untitled"),      "picture": picture.asset->url    },    "page": *[_type == "programmePage" && programme._ref == ^._id && language == $language][0] {      "slug": slug.current,      description    }  }
export type ProgrammesQueryResult = Array<{
  _id: string;
  email: string | null;
  title: string | "Untitled";
  managers: Array<{
    _id: string;
    name: string | "Untitled";
    picture: string | null;
  }> | null;
  page: {
    slug: string | null;
    description: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  } | null;
}>;
// Variable: programmePageQuery
// Query: *[_type == "programmePage" && slug.current == $slug && language == $language][0] {    _id,    "slug": slug.current,    description,    "programme": programme->{      _id,      "title": coalesce(title, "Untitled"),      email,      "managers": managers[]->{        _id,        "name": coalesce(name, "Untitled"),        picture,        biography      }    }  }
export type ProgrammePageQueryResult = {
  _id: string;
  slug: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  programme: {
    _id: string;
    title: string | "Untitled";
    email: string | null;
    managers: Array<{
      _id: string;
      name: string | "Untitled";
      picture: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      biography: InternationalizedArrayString | null;
    }> | null;
  } | null;
} | null;
// Variable: eventsByProgrammeQuery
// Query: *[_type == "event" && programme._ref == $programmeId && language == $language] | order(start desc) {    _id,    "title": coalesce(title, "Untitled"),    "slug": slug.current,    type,    location,    start,    end,    "image": image.asset->url,    description  }
export type EventsByProgrammeQueryResult = Array<{
  _id: string;
  title: string | "Untitled";
  slug: string | null;
  type: "ga" | "seminar" | "workshop" | null;
  location: string | null;
  start: string | null;
  end: string | null;
  image: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
}>;
// Variable: peopleQuery
// Query: *[_type == "role" && dateTime($date) >= dateTime(start + 'T00:00:00Z') && (dateTime($date) < dateTime(end + 'T00:00:00Z') || !defined(end))] {    _id,    type,    email,    title,    bureauRole,    officeRole,    "organization": organization->name,    "name": person->name,    "picture": person->picture.asset->url  }
export type PeopleQueryResult = Array<{
  _id: string;
  type: "advisory-council" | "bureau-member" | "honorary-member" | "individual-member" | "office" | "ombudsperson" | "regional-representative" | null;
  email: string | null;
  title: string | null;
  bureauRole: "president" | "secretary-general" | "treasurer" | "vice-president" | null;
  officeRole: "executive-director" | "intern" | "project-manager" | null;
  organization: string | null;
  name: string | null;
  picture: string | null;
}>;
// Variable: peopleArchiveQuery
// Query: *[_type == "role" && defined(end) && dateTime(end + 'T00:00:00Z') < dateTime($currentDate)] | order(end desc) {    _id,    type,    email,    title,    bureauRole,    officeRole,    "organization": organization->name,    "name": person->name,    "picture": person->picture.asset->url,    start,    end  }
export type PeopleArchiveQueryResult = Array<{
  _id: string;
  type: "advisory-council" | "bureau-member" | "honorary-member" | "individual-member" | "office" | "ombudsperson" | "regional-representative" | null;
  email: string | null;
  title: string | null;
  bureauRole: "president" | "secretary-general" | "treasurer" | "vice-president" | null;
  officeRole: "executive-director" | "intern" | "project-manager" | null;
  organization: string | null;
  name: string | null;
  picture: string | null;
  start: string | null;
  end: string | null;
}>;
// Variable: eventsQuery
// Query: *[_type == "event" && language == $language] | order(start desc) {    _id,    "title": coalesce(title, "Untitled"),    "slug": slug.current,    type,    location,    start,    end,    "image": image.asset->url,    description,    "contactPerson": {      "person": contactPerson.person->{        _id,        "name": coalesce(name, "Untitled"),        "picture": picture.asset->url      },      "email": contactPerson.email    },    "trainers": trainers[]->{      _id,      email,      expertises,      languages,      "person": person->{        _id,        "name": coalesce(name, "Untitled"),        "picture": picture.asset->url,        biography      }    }  }
export type EventsQueryResult = Array<{
  _id: string;
  title: string | "Untitled";
  slug: string | null;
  type: "ga" | "seminar" | "workshop" | null;
  location: string | null;
  start: string | null;
  end: string | null;
  image: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  contactPerson: {
    person: {
      _id: string;
      name: string | "Untitled";
      picture: string | null;
    } | null;
    email: string | null;
  };
  trainers: Array<{
    _id: string;
    email: string | null;
    expertises: Array<string> | null;
    languages: Array<"ar" | "de" | "en" | "es" | "fr" | "it" | "ja" | "nl" | "pt" | "ru" | "zh"> | null;
    person: {
      _id: string;
      name: string | "Untitled";
      picture: string | null;
      biography: InternationalizedArrayString | null;
    } | null;
  }> | null;
}>;
// Variable: upcomingEventsQuery
// Query: *[_type == "event" && language == $language && dateTime(start) >= dateTime($currentDate)] | order(start asc) [$offset...$limit] {      _id,  "title": coalesce(title, "Untitled"),  "slug": slug.current,  type,  location,  start,  end,  "image": image.asset->url,  description,  "contactPerson": {    "person": contactPerson.person->{      _id,      "name": coalesce(name, "Untitled"),      "picture": picture.asset->url    },    "email": contactPerson.email  },  registrationLink,  registrationDeadline,  "attachments": attachments[]{ "title": coalesce(title, "Document"), "url": asset->url },  "trainers": trainers[]->{    _id,    email,    expertises,    languages,    "person": person->{      _id,      "name": coalesce(name, "Untitled"),      "picture": picture.asset->url,      biography    }  }  }
export type UpcomingEventsQueryResult = Array<{
  _id: string;
  title: string | "Untitled";
  slug: string | null;
  type: "ga" | "seminar" | "workshop" | null;
  location: string | null;
  start: string | null;
  end: string | null;
  image: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  contactPerson: {
    person: {
      _id: string;
      name: string | "Untitled";
      picture: string | null;
    } | null;
    email: string | null;
  };
  registrationLink: string | null;
  registrationDeadline: string | null;
  attachments: Array<{
    title: string | "Document";
    url: string | null;
  }> | null;
  trainers: Array<{
    _id: string;
    email: string | null;
    expertises: Array<string> | null;
    languages: Array<"ar" | "de" | "en" | "es" | "fr" | "it" | "ja" | "nl" | "pt" | "ru" | "zh"> | null;
    person: {
      _id: string;
      name: string | "Untitled";
      picture: string | null;
      biography: InternationalizedArrayString | null;
    } | null;
  }> | null;
}>;
// Variable: upcomingEventsCountQuery
// Query: count(*[_type == "event" && language == $language && dateTime(start) >= dateTime($currentDate)])
export type UpcomingEventsCountQueryResult = number;
// Variable: pastEventsQuery
// Query: *[_type == "event" && language == $language && dateTime(start) < dateTime($currentDate)] | order(start desc) [$offset...$limit] {      _id,  "title": coalesce(title, "Untitled"),  "slug": slug.current,  type,  location,  start,  end,  "image": image.asset->url,  description,  "contactPerson": {    "person": contactPerson.person->{      _id,      "name": coalesce(name, "Untitled"),      "picture": picture.asset->url    },    "email": contactPerson.email  },  registrationLink,  registrationDeadline,  "attachments": attachments[]{ "title": coalesce(title, "Document"), "url": asset->url },  "trainers": trainers[]->{    _id,    email,    expertises,    languages,    "person": person->{      _id,      "name": coalesce(name, "Untitled"),      "picture": picture.asset->url,      biography    }  }  }
export type PastEventsQueryResult = Array<{
  _id: string;
  title: string | "Untitled";
  slug: string | null;
  type: "ga" | "seminar" | "workshop" | null;
  location: string | null;
  start: string | null;
  end: string | null;
  image: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  contactPerson: {
    person: {
      _id: string;
      name: string | "Untitled";
      picture: string | null;
    } | null;
    email: string | null;
  };
  registrationLink: string | null;
  registrationDeadline: string | null;
  attachments: Array<{
    title: string | "Document";
    url: string | null;
  }> | null;
  trainers: Array<{
    _id: string;
    email: string | null;
    expertises: Array<string> | null;
    languages: Array<"ar" | "de" | "en" | "es" | "fr" | "it" | "ja" | "nl" | "pt" | "ru" | "zh"> | null;
    person: {
      _id: string;
      name: string | "Untitled";
      picture: string | null;
      biography: InternationalizedArrayString | null;
    } | null;
  }> | null;
}>;
// Variable: pastEventsCountQuery
// Query: count(*[_type == "event" && language == $language && dateTime(start) < dateTime($currentDate)])
export type PastEventsCountQueryResult = number;
// Variable: eventQuery
// Query: *[_type == "event" && slug.current == $slug && language == $language] [0] {    _id,    "title": coalesce(title, "Untitled"),    "slug": slug.current,    type,    location,    start,    end,    image,    description,    "contactPerson": {      "person": contactPerson.person->{        _id,        "name": coalesce(name, "Untitled"),        "picture": picture.asset->url      },      "email": contactPerson.email    },    "programme": programme->{      _id,      "title": coalesce(title, "Untitled"),      email    },    "partners": partners[]->{      _id,      "title": coalesce(title, "Untitled"),      "logo": logo.asset->url,      description    },    "members": members[]->{      _id,      _type,      name,      memberId,      "logo": logo.asset->url    },    registrationLink,    registrationDeadline,    "attachments": attachments[]{ "title": coalesce(title, "Document"), "url": asset->url },    "trainers": trainers[]->{      _id,      email,      expertises,      languages,      "person": person->{        _id,        "name": coalesce(name, "Untitled"),        "picture": picture.asset->url,        biography      }    }  }
export type EventQueryResult = {
  _id: string;
  title: string | "Untitled";
  slug: string | null;
  type: "ga" | "seminar" | "workshop" | null;
  location: string | null;
  start: string | null;
  end: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  contactPerson: {
    person: {
      _id: string;
      name: string | "Untitled";
      picture: string | null;
    } | null;
    email: string | null;
  };
  programme: {
    _id: string;
    title: string | "Untitled";
    email: string | null;
  } | null;
  partners: Array<{
    _id: string;
    title: string | "Untitled";
    logo: string | null;
    description: Array<{
      _key: string;
    } & InternationalizedArrayStringValue> | null;
  }> | null;
  members: Array<{
    _id: string;
    _type: "memberOrganisation";
    name: string | null;
    memberId: string | null;
    logo: string | null;
  } | {
    _id: string;
    _type: "regionalNetwork";
    name: string | null;
    memberId: string | null;
    logo: string | null;
  }> | null;
  registrationLink: string | null;
  registrationDeadline: string | null;
  attachments: Array<{
    title: string | "Document";
    url: string | null;
  }> | null;
  trainers: Array<{
    _id: string;
    email: string | null;
    expertises: Array<string> | null;
    languages: Array<"ar" | "de" | "en" | "es" | "fr" | "it" | "ja" | "nl" | "pt" | "ru" | "zh"> | null;
    person: {
      _id: string;
      name: string | "Untitled";
      picture: string | null;
      biography: InternationalizedArrayString | null;
    } | null;
  }> | null;
} | null;
// Variable: vacanciesQuery
// Query: *[_type == "vacancy" && language == $language] | order(deadline asc) {    _id,    "title": coalesce(title, "Untitled"),    "slug": slug.current,    image,    location,    deadline  }
export type VacanciesQueryResult = Array<{
  _id: string;
  title: string | "Untitled";
  slug: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  location: string | null;
  deadline: string | null;
}>;
// Variable: vacancyQuery
// Query: *[_type == "vacancy" && slug.current == $slug && language == $language][0] {    _id,    "title": coalesce(title, "Untitled"),    "slug": slug.current,    description,    image,    location,    applicationUrl,    deadline  }
export type VacancyQueryResult = {
  _id: string;
  title: string | "Untitled";
  slug: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  location: string | null;
  applicationUrl: string | null;
  deadline: string | null;
} | null;
// Variable: trainersQuery
// Query: *[_type == "trainer" && displayAsTrainer == true] {    _id,    email,    expertises,    languages,    "person": person->{      _id,      "name": coalesce(name, "Untitled"),      picture,      biography    }  }
export type TrainersQueryResult = Array<{
  _id: string;
  email: string | null;
  expertises: Array<string> | null;
  languages: Array<"ar" | "de" | "en" | "es" | "fr" | "it" | "ja" | "nl" | "pt" | "ru" | "zh"> | null;
  person: {
    _id: string;
    name: string | "Untitled";
    picture: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    biography: InternationalizedArrayString | null;
  } | null;
}>;
// Variable: memberOrganisationsQuery
// Query: *[_type == "memberOrganisation"] | order(name asc) {    _id,    name,    memberId,    country,    countryName,    membershipType,    primaryRegion,    secondaryRegion,    votes,    "logo": logo.asset->url,    website,    wiki,    fb,    twitter,    ig  }
export type MemberOrganisationsQueryResult = Array<{
  _id: string;
  name: string | null;
  memberId: string | null;
  country: string | null;
  countryName: string | null;
  membershipType: "associate" | "full" | "observer" | null;
  primaryRegion: "Africa" | "Asia-Pacific" | "Caucasus" | "Eastern Europe" | "Latin America" | "MENA" | "North America and Israel" | "Western Europe" | null;
  secondaryRegion: "Africa" | "Asia-Pacific" | "Caucasus" | "Eastern Europe" | "Latin America" | "MENA" | "North America and Israel" | "Western Europe" | null;
  votes: number | null;
  logo: string | null;
  website: string | null;
  wiki: string | null;
  fb: string | null;
  twitter: string | null;
  ig: string | null;
}>;
// Variable: regionalNetworksQuery
// Query: *[_type == "regionalNetwork"] | order(name asc) {    _id,    name,    fullName,    memberId,    region,    "logo": logo.asset->url,    website,    wiki,    fb,    twitter,    ig  }
export type RegionalNetworksQueryResult = Array<{
  _id: string;
  name: string | null;
  fullName: string | null;
  memberId: string | null;
  region: string | null;
  logo: string | null;
  website: string | null;
  wiki: string | null;
  fb: string | null;
  twitter: string | null;
  ig: string | null;
}>;

// Source: ./src/app/(content)/[locale]/events/[slug]/page.tsx
// Variable: eventSlugs
// Query: *[_type == "event" && defined(slug.current)]{"slug": slug.current, language}
export type EventSlugsResult = Array<{
  slug: string | null;
  language: string | null;
}>;

// Source: ./src/app/(content)/[locale]/pages/[slug]/page.tsx
// Variable: pageSlugs
// Query: *[_type == "page" && defined(slug.current)]{"slug": slug.current}
export type PageSlugsResult = Array<{
  slug: string | null;
}>;

// Source: ./src/app/(content)/[locale]/posts/[slug]/page.tsx
// Variable: postSlugs
// Query: *[_type == "post" && defined(slug.current)]{"slug": slug.current}
export type PostSlugsResult = Array<{
  slug: string | null;
}>;

// Source: ./src/app/(content)/[locale]/programmes/[slug]/page.tsx
// Variable: programmePageSlugs
// Query: *[_type == "programmePage" && defined(slug.current)]{"slug": slug.current, language}
export type ProgrammePageSlugsResult = Array<{
  slug: string | null;
  language: string | null;
}>;

// Source: ./src/app/(content)/[locale]/vacancies/[slug]/page.tsx
// Variable: vacancySlugs
// Query: *[_type == "vacancy" && defined(slug.current)]{"slug": slug.current, language}
export type VacancySlugsResult = Array<{
  slug: string | null;
  language: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"configuration\" && language == $language][0] {\n    ...,\n    navigation[] {\n      title,\n      linkType,\n      page-> {\n        slug,\n        type\n      },\n      customUrl,\n      children[] {\n        title,\n        linkType,\n        page-> {\n          slug,\n          type\n        },\n        customUrl,\n        children[] {\n          title,\n          linkType,\n          page-> {\n            slug,\n            type\n          },\n          customUrl,\n          children[] {\n            title,\n            linkType,\n            page-> {\n              slug,\n              type\n            },\n            customUrl\n          }\n        }\n      }\n    },\n    announcementBanner {\n      enabled,\n      text,\n      cta,\n      href\n    },\n    footer {\n      fineprint,\n      columns[] {\n        title,\n        links[] {\n          title,\n          linkType,\n          page-> {\n            slug,\n            type\n          },\n          customUrl\n        }\n      },\n      socialLinks[] {\n        platform,\n        url\n      }\n    }\n  }\n": SettingsQueryResult;
    "\n  *[_type == \"post\" && defined(slug.current) && language == $language] | order(date desc, _updatedAt desc) [0...$quantity] {\n    content,\n    \n  _id,\n  \"status\": select(_originalId in path(\"drafts.**\") => \"draft\", \"published\"),\n  \"title\": coalesce(title, \"Untitled\"),\n  \"slug\": slug.current,\n  type,\n  image,\n  \"date\": coalesce(date, _updatedAt),\n  \"author\": author->{\"name\": coalesce(name, \"Anonymous\"), picture},\n  \"attachments\": attachments[]{ \"title\": coalesce(title, \"Document\"), \"url\": asset->url },\n\n  }\n": FeaturedPostsQueryResult;
    "\n  *[_type == \"post\" && defined(slug.current) && language == $language && ($type == \"\" || type == $type)] | order(date desc, _updatedAt desc) [$offset...$limit] {\n    \n  _id,\n  \"status\": select(_originalId in path(\"drafts.**\") => \"draft\", \"published\"),\n  \"title\": coalesce(title, \"Untitled\"),\n  \"slug\": slug.current,\n  type,\n  image,\n  \"date\": coalesce(date, _updatedAt),\n  \"author\": author->{\"name\": coalesce(name, \"Anonymous\"), picture},\n  \"attachments\": attachments[]{ \"title\": coalesce(title, \"Document\"), \"url\": asset->url },\n\n  }\n": PostsQueryResult;
    "\n  count(*[_type == \"post\" && defined(slug.current) && language == $language && ($type == \"\" || type == $type)])\n": PostsCountQueryResult;
    "\n  *[_type == \"post\" && _id != $skip && defined(slug.current) && language == $language] | order(date desc, _updatedAt desc) [0...$limit] {\n    \n  _id,\n  \"status\": select(_originalId in path(\"drafts.**\") => \"draft\", \"published\"),\n  \"title\": coalesce(title, \"Untitled\"),\n  \"slug\": slug.current,\n  type,\n  image,\n  \"date\": coalesce(date, _updatedAt),\n  \"author\": author->{\"name\": coalesce(name, \"Anonymous\"), picture},\n  \"attachments\": attachments[]{ \"title\": coalesce(title, \"Document\"), \"url\": asset->url },\n\n  }\n": MoreStoriesQueryResult;
    "\n  *[_type == \"post\" && slug.current == $slug && language == $language] [0] {\n    content,\n    \n  _id,\n  \"status\": select(_originalId in path(\"drafts.**\") => \"draft\", \"published\"),\n  \"title\": coalesce(title, \"Untitled\"),\n  \"slug\": slug.current,\n  type,\n  image,\n  \"date\": coalesce(date, _updatedAt),\n  \"author\": author->{\"name\": coalesce(name, \"Anonymous\"), picture},\n  \"attachments\": attachments[]{ \"title\": coalesce(title, \"Document\"), \"url\": asset->url },\n\n  }\n": PostQueryResult;
    "\n  *[_type == \"page\" && slug.current == $slug && language == $language] [0] {\n    _id,\n    content,\n    \"title\": coalesce(title, \"Untitled\"),\n    \"slug\": slug.current,\n  }\n": PageQueryResult;
    "\n  *[_type == \"page\" && type == $type && language == $language] [0] {\n    _id,\n    content,\n    \"title\": coalesce(title, \"Untitled\"),\n  }\n": PageTypeQueryResult;
    "\n  *[_type == \"partner\" && displayAsPartner == true] {\n    _id,\n    \"title\": coalesce(title, \"Untitled\"),\n    \"logo\": logo.asset->url,\n    description\n  }\n": PartnersQueryResult;
    "\n  *[_type == \"donationItem\"] | order(order asc) {\n    _id,\n    \"title\": coalesce(title, \"Untitled\"),\n    description,\n    \"imageUrl\": image.asset->url,\n    \"programme\": programme->{ _id, name },\n    amount,\n    oneOffLink,\n    recurringLink\n  }\n": DonationItemsQueryResult;
    "\n  *[_type == \"coreDocument\"] | order(order asc) {\n    _id,\n    \"title\": coalesce(title, \"Untitled\"),\n    description,\n    \"fileUrl\": file.asset->url\n  }\n": CoreDocumentsQueryResult;
    "\n  *[_type == \"programme\"] {\n    _id,\n    email,\n    \"title\": coalesce(title, \"Untitled\"),\n    \"managers\": managers[]->{\n      _id,\n      \"name\": coalesce(name, \"Untitled\"),\n      \"picture\": picture.asset->url\n    },\n    \"page\": *[_type == \"programmePage\" && programme._ref == ^._id && language == $language][0] {\n      \"slug\": slug.current,\n      description\n    }\n  }\n": ProgrammesQueryResult;
    "\n  *[_type == \"programmePage\" && slug.current == $slug && language == $language][0] {\n    _id,\n    \"slug\": slug.current,\n    description,\n    \"programme\": programme->{\n      _id,\n      \"title\": coalesce(title, \"Untitled\"),\n      email,\n      \"managers\": managers[]->{\n        _id,\n        \"name\": coalesce(name, \"Untitled\"),\n        picture,\n        biography\n      }\n    }\n  }\n": ProgrammePageQueryResult;
    "\n  *[_type == \"event\" && programme._ref == $programmeId && language == $language] | order(start desc) {\n    _id,\n    \"title\": coalesce(title, \"Untitled\"),\n    \"slug\": slug.current,\n    type,\n    location,\n    start,\n    end,\n    \"image\": image.asset->url,\n    description\n  }\n": EventsByProgrammeQueryResult;
    "\n  *[_type == \"role\" && dateTime($date) >= dateTime(start + 'T00:00:00Z') && (dateTime($date) < dateTime(end + 'T00:00:00Z') || !defined(end))] {\n    _id,\n    type,\n    email,\n    title,\n    bureauRole,\n    officeRole,\n    \"organization\": organization->name,\n    \"name\": person->name,\n    \"picture\": person->picture.asset->url\n  }\n": PeopleQueryResult;
    "\n  *[_type == \"role\" && defined(end) && dateTime(end + 'T00:00:00Z') < dateTime($currentDate)] | order(end desc) {\n    _id,\n    type,\n    email,\n    title,\n    bureauRole,\n    officeRole,\n    \"organization\": organization->name,\n    \"name\": person->name,\n    \"picture\": person->picture.asset->url,\n    start,\n    end\n  }\n": PeopleArchiveQueryResult;
    "\n  *[_type == \"event\" && language == $language] | order(start desc) {\n    _id,\n    \"title\": coalesce(title, \"Untitled\"),\n    \"slug\": slug.current,\n    type,\n    location,\n    start,\n    end,\n    \"image\": image.asset->url,\n    description,\n    \"contactPerson\": {\n      \"person\": contactPerson.person->{\n        _id,\n        \"name\": coalesce(name, \"Untitled\"),\n        \"picture\": picture.asset->url\n      },\n      \"email\": contactPerson.email\n    },\n    \"trainers\": trainers[]->{\n      _id,\n      email,\n      expertises,\n      languages,\n      \"person\": person->{\n        _id,\n        \"name\": coalesce(name, \"Untitled\"),\n        \"picture\": picture.asset->url,\n        biography\n      }\n    }\n  }\n": EventsQueryResult;
    "\n  *[_type == \"event\" && language == $language && dateTime(start) >= dateTime($currentDate)] | order(start asc) [$offset...$limit] {\n    \n  _id,\n  \"title\": coalesce(title, \"Untitled\"),\n  \"slug\": slug.current,\n  type,\n  location,\n  start,\n  end,\n  \"image\": image.asset->url,\n  description,\n  \"contactPerson\": {\n    \"person\": contactPerson.person->{\n      _id,\n      \"name\": coalesce(name, \"Untitled\"),\n      \"picture\": picture.asset->url\n    },\n    \"email\": contactPerson.email\n  },\n  registrationLink,\n  registrationDeadline,\n  \"attachments\": attachments[]{ \"title\": coalesce(title, \"Document\"), \"url\": asset->url },\n  \"trainers\": trainers[]->{\n    _id,\n    email,\n    expertises,\n    languages,\n    \"person\": person->{\n      _id,\n      \"name\": coalesce(name, \"Untitled\"),\n      \"picture\": picture.asset->url,\n      biography\n    }\n  }\n\n  }\n": UpcomingEventsQueryResult;
    "\n  count(*[_type == \"event\" && language == $language && dateTime(start) >= dateTime($currentDate)])\n": UpcomingEventsCountQueryResult;
    "\n  *[_type == \"event\" && language == $language && dateTime(start) < dateTime($currentDate)] | order(start desc) [$offset...$limit] {\n    \n  _id,\n  \"title\": coalesce(title, \"Untitled\"),\n  \"slug\": slug.current,\n  type,\n  location,\n  start,\n  end,\n  \"image\": image.asset->url,\n  description,\n  \"contactPerson\": {\n    \"person\": contactPerson.person->{\n      _id,\n      \"name\": coalesce(name, \"Untitled\"),\n      \"picture\": picture.asset->url\n    },\n    \"email\": contactPerson.email\n  },\n  registrationLink,\n  registrationDeadline,\n  \"attachments\": attachments[]{ \"title\": coalesce(title, \"Document\"), \"url\": asset->url },\n  \"trainers\": trainers[]->{\n    _id,\n    email,\n    expertises,\n    languages,\n    \"person\": person->{\n      _id,\n      \"name\": coalesce(name, \"Untitled\"),\n      \"picture\": picture.asset->url,\n      biography\n    }\n  }\n\n  }\n": PastEventsQueryResult;
    "\n  count(*[_type == \"event\" && language == $language && dateTime(start) < dateTime($currentDate)])\n": PastEventsCountQueryResult;
    "\n  *[_type == \"event\" && slug.current == $slug && language == $language] [0] {\n    _id,\n    \"title\": coalesce(title, \"Untitled\"),\n    \"slug\": slug.current,\n    type,\n    location,\n    start,\n    end,\n    image,\n    description,\n    \"contactPerson\": {\n      \"person\": contactPerson.person->{\n        _id,\n        \"name\": coalesce(name, \"Untitled\"),\n        \"picture\": picture.asset->url\n      },\n      \"email\": contactPerson.email\n    },\n    \"programme\": programme->{\n      _id,\n      \"title\": coalesce(title, \"Untitled\"),\n      email\n    },\n    \"partners\": partners[]->{\n      _id,\n      \"title\": coalesce(title, \"Untitled\"),\n      \"logo\": logo.asset->url,\n      description\n    },\n    \"members\": members[]->{\n      _id,\n      _type,\n      name,\n      memberId,\n      \"logo\": logo.asset->url\n    },\n    registrationLink,\n    registrationDeadline,\n    \"attachments\": attachments[]{ \"title\": coalesce(title, \"Document\"), \"url\": asset->url },\n    \"trainers\": trainers[]->{\n      _id,\n      email,\n      expertises,\n      languages,\n      \"person\": person->{\n        _id,\n        \"name\": coalesce(name, \"Untitled\"),\n        \"picture\": picture.asset->url,\n        biography\n      }\n    }\n  }\n": EventQueryResult;
    "\n  *[_type == \"vacancy\" && language == $language] | order(deadline asc) {\n    _id,\n    \"title\": coalesce(title, \"Untitled\"),\n    \"slug\": slug.current,\n    image,\n    location,\n    deadline\n  }\n": VacanciesQueryResult;
    "\n  *[_type == \"vacancy\" && slug.current == $slug && language == $language][0] {\n    _id,\n    \"title\": coalesce(title, \"Untitled\"),\n    \"slug\": slug.current,\n    description,\n    image,\n    location,\n    applicationUrl,\n    deadline\n  }\n": VacancyQueryResult;
    "\n  *[_type == \"trainer\" && displayAsTrainer == true] {\n    _id,\n    email,\n    expertises,\n    languages,\n    \"person\": person->{\n      _id,\n      \"name\": coalesce(name, \"Untitled\"),\n      picture,\n      biography\n    }\n  }\n": TrainersQueryResult;
    "\n  *[_type == \"memberOrganisation\"] | order(name asc) {\n    _id,\n    name,\n    memberId,\n    country,\n    countryName,\n    membershipType,\n    primaryRegion,\n    secondaryRegion,\n    votes,\n    \"logo\": logo.asset->url,\n    website,\n    wiki,\n    fb,\n    twitter,\n    ig\n  }\n": MemberOrganisationsQueryResult;
    "\n  *[_type == \"regionalNetwork\"] | order(name asc) {\n    _id,\n    name,\n    fullName,\n    memberId,\n    region,\n    \"logo\": logo.asset->url,\n    website,\n    wiki,\n    fb,\n    twitter,\n    ig\n  }\n": RegionalNetworksQueryResult;
    "*[_type == \"event\" && defined(slug.current)]{\"slug\": slug.current, language}": EventSlugsResult;
    "*[_type == \"page\" && defined(slug.current)]{\"slug\": slug.current}": PageSlugsResult;
    "*[_type == \"post\" && defined(slug.current)]{\"slug\": slug.current}": PostSlugsResult;
    "*[_type == \"programmePage\" && defined(slug.current)]{\"slug\": slug.current, language}": ProgrammePageSlugsResult;
    "*[_type == \"vacancy\" && defined(slug.current)]{\"slug\": slug.current, language}": VacancySlugsResult;
  }
}
