/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type NavigationItem = {
  _type: "navigationItem";
  title?: string;
  linkType?: "page" | "events" | "posts" | "trainers" | "vacancies" | "custom" | "submenu";
  page?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  };
  customUrl?: string;
  children?: Array<{
    _key: string;
  } & NavigationItem>;
};

export type Trainer = {
  _id: string;
  _type: "trainer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  person?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "person";
  };
  email?: string;
  expertises?: Array<string>;
  languages?: Array<"en" | "fr" | "es" | "de" | "nl" | "it" | "pt" | "ru" | "ar" | "zh" | "ja">;
};

export type Role = {
  _id: string;
  _type: "role";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  type?: "bureau-member" | "ombudsperson" | "advisory-council" | "regional-representative" | "office" | "individual-member" | "honorary-member";
  bureauRole?: "president" | "secretary-general" | "treasurer" | "vice-president";
  officeRole?: "executive-director" | "intern" | "project-manager";
  organization?: "LYMEC" | "CALD" | "ALYF" | "JULAC";
  person?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "person";
  };
  title?: string;
  email?: string;
  start?: string;
  end?: string;
};

export type Member = {
  _id: string;
  _type: "member";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  memberId?: "ARG-GJFL" | "LVA-PARJ" | "AND-JLA" | "MKD-LDM" | "BIH-YFNS" | "BGR-YMRF" | "PRY-JLRA" | "BOL-NMJ" | "BFA-FL" | "SYR-AYLS" | "TUR-3HM" | "FRA-JR" | "CHE-JS" | "GIN-OJLG" | "POL-NY" | "SVK-YP" | "GIN-CNJR" | "SEN-PCR" | "SEN-JLS" | "COD-JEPR" | "SDN-FYSO" | "SEN-CEEP" | "ARM-ANC" | "UKR-EYU" | "EST-NE2" | "MAR-AJA" | "SEN-JLD" | "KEN-ODM" | "GRC-NEON" | "BLR-CF" | "MRT-FCA" | "COG-CLE" | "USA-YDA" | "EGY-EL" | "SEN-RM" | "BFA-RNJL" | "TZA-ACTW" | "GHA-PYM" | "BEL-JVLD" | "MAR-HRK" | "GEO-IIL" | "SEN-FJR" | "CIV-JALIDE" | "MAR-CDC" | "LBN-FY" | "CIV-JELIC" | "BLR-YB" | "SEN-MFA" | "TZA-PYI" | "CIV-OJLCI" | "LTU-LLJ" | "ISR-YYA" | "BAS-EGI" | "GHA-YLG" | "DEU-LHG" | "GBR-YL" | "IRQ-VIO" | "NIC-AVZ" | "IRQ-SASA" | "AZE-PH" | "AUT-JUNOS" | "CAT-JNC" | "EGY-EYC" | "SEN-COJER" | "ROU-USRT" | "GEO-FK" | "BEL-FEL" | "NLD-JD" | "CHL-JE" | "DNK-VU" | "NOR-NUV" | "NLD-JOVD" | "FIN-SU" | "DNK-LAU" | "SWE-CUF" | "FIN-FCY" | "JOR-S42" | "HUN-MT" | "RUS-YDMV" | "NPL-YI" | "NOR-NLS" | "UKR-LDLU" | "JOR-FTF" | "DNK-RU" | "SWE-LUF" | "DEU-JULIS" | "CIV-RHDP" | "CAN-YLC" | "HRV-IDY" | "HRV-MHNS" | "GIB-GLY" | "MNE-YLM" | "PER-IPL" | "ZAF-DAY" | "VEN-VJ" | "LYMEC" | "CALD" | "ALYF" | "JULAC";
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  website?: string;
  wiki?: string;
  fb?: string;
  twitter?: string;
  ig?: string;
};

export type Partner = {
  _id: string;
  _type: "partner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  biography?: Array<{
    _key: string;
  } & InternationalizedArrayStringValue>;
  description?: Array<{
    _key: string;
  } & InternationalizedArrayStringValue>;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Configuration = {
  _id: string;
  _type: "configuration";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  navigation?: Array<{
    _key: string;
  } & NavigationItem>;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    metadataBase?: string;
    _type: "image";
  };
};

export type InternationalizedArrayStringValue = {
  _type: "internationalizedArrayStringValue";
  value?: string;
};

export type InternationalizedArrayString = Array<{
  _key: string;
} & InternationalizedArrayStringValue>;

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: Array<{
    _key: string;
  } & InternationalizedArrayReferenceValue>;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "post";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "event";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "vacancy";
  };
};

export type Vacancy = {
  _id: string;
  _type: "vacancy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  title?: string;
  description?: InternationalizedArrayString;
  location?: string;
  applicationUrl?: string;
  deadline?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  language?: string;
  type?: "members" | "partners" | "programmes" | "people" | "other";
  slug?: Slug;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  createdAt?: string;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  contactPerson?: {
    person?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "person";
    };
    email?: string;
  };
  type?: "ga" | "seminar" | "workshop";
  slug?: Slug;
  location?: string;
  start?: string;
  end?: string;
  language?: string;
  programme?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "programme";
  };
  members?: Array<"ARG-GJFL" | "LVA-PARJ" | "AND-JLA" | "MKD-LDM" | "BIH-YFNS" | "BGR-YMRF" | "PRY-JLRA" | "BOL-NMJ" | "BFA-FL" | "SYR-AYLS" | "TUR-3HM" | "FRA-JR" | "CHE-JS" | "GIN-OJLG" | "POL-NY" | "SVK-YP" | "GIN-CNJR" | "SEN-PCR" | "SEN-JLS" | "COD-JEPR" | "SDN-FYSO" | "SEN-CEEP" | "ARM-ANC" | "UKR-EYU" | "EST-NE2" | "MAR-AJA" | "SEN-JLD" | "KEN-ODM" | "GRC-NEON" | "BLR-CF" | "MRT-FCA" | "COG-CLE" | "USA-YDA" | "EGY-EL" | "SEN-RM" | "BFA-RNJL" | "TZA-ACTW" | "GHA-PYM" | "BEL-JVLD" | "MAR-HRK" | "GEO-IIL" | "SEN-FJR" | "CIV-JALIDE" | "MAR-CDC" | "LBN-FY" | "CIV-JELIC" | "BLR-YB" | "SEN-MFA" | "TZA-PYI" | "CIV-OJLCI" | "LTU-LLJ" | "ISR-YYA" | "BAS-EGI" | "GHA-YLG" | "DEU-LHG" | "GBR-YL" | "IRQ-VIO" | "NIC-AVZ" | "IRQ-SASA" | "AZE-PH" | "AUT-JUNOS" | "CAT-JNC" | "EGY-EYC" | "SEN-COJER" | "ROU-USRT" | "GEO-FK" | "BEL-FEL" | "NLD-JD" | "CHL-JE" | "DNK-VU" | "NOR-NUV" | "NLD-JOVD" | "FIN-SU" | "DNK-LAU" | "SWE-CUF" | "FIN-FCY" | "JOR-S42" | "HUN-MT" | "RUS-YDMV" | "NPL-YI" | "NOR-NLS" | "UKR-LDLU" | "JOR-FTF" | "DNK-RU" | "SWE-LUF" | "DEU-JULIS" | "CIV-RHDP" | "CAN-YLC" | "HRV-IDY" | "HRV-MHNS" | "GIB-GLY" | "MNE-YLM" | "PER-IPL" | "ZAF-DAY" | "VEN-VJ" | "LYMEC" | "CALD" | "ALYF" | "JULAC">;
  partners?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "partner";
  }>;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: InternationalizedArrayString;
  trainers?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "trainer";
  }>;
};

export type Programme = {
  _id: string;
  _type: "programme";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  managers?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "person";
  }>;
  email?: string;
  description?: InternationalizedArrayString;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  language?: string;
  type?: "statement" | "press-release" | "bureau-update";
  slug?: Slug;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  date?: string;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "person";
  };
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  biography?: InternationalizedArrayString;
  picture?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  organization?: "ARG-GJFL" | "LVA-PARJ" | "AND-JLA" | "MKD-LDM" | "BIH-YFNS" | "BGR-YMRF" | "PRY-JLRA" | "BOL-NMJ" | "BFA-FL" | "SYR-AYLS" | "TUR-3HM" | "FRA-JR" | "CHE-JS" | "GIN-OJLG" | "POL-NY" | "SVK-YP" | "GIN-CNJR" | "SEN-PCR" | "SEN-JLS" | "COD-JEPR" | "SDN-FYSO" | "SEN-CEEP" | "ARM-ANC" | "UKR-EYU" | "EST-NE2" | "MAR-AJA" | "SEN-JLD" | "KEN-ODM" | "GRC-NEON" | "BLR-CF" | "MRT-FCA" | "COG-CLE" | "USA-YDA" | "EGY-EL" | "SEN-RM" | "BFA-RNJL" | "TZA-ACTW" | "GHA-PYM" | "BEL-JVLD" | "MAR-HRK" | "GEO-IIL" | "SEN-FJR" | "CIV-JALIDE" | "MAR-CDC" | "LBN-FY" | "CIV-JELIC" | "BLR-YB" | "SEN-MFA" | "TZA-PYI" | "CIV-OJLCI" | "LTU-LLJ" | "ISR-YYA" | "BAS-EGI" | "GHA-YLG" | "DEU-LHG" | "GBR-YL" | "IRQ-VIO" | "NIC-AVZ" | "IRQ-SASA" | "AZE-PH" | "AUT-JUNOS" | "CAT-JNC" | "EGY-EYC" | "SEN-COJER" | "ROU-USRT" | "GEO-FK" | "BEL-FEL" | "NLD-JD" | "CHL-JE" | "DNK-VU" | "NOR-NUV" | "NLD-JOVD" | "FIN-SU" | "DNK-LAU" | "SWE-CUF" | "FIN-FCY" | "JOR-S42" | "HUN-MT" | "RUS-YDMV" | "NPL-YI" | "NOR-NLS" | "UKR-LDLU" | "JOR-FTF" | "DNK-RU" | "SWE-LUF" | "DEU-JULIS" | "CIV-RHDP" | "CAN-YLC" | "HRV-IDY" | "HRV-MHNS" | "GIB-GLY" | "MNE-YLM" | "PER-IPL" | "ZAF-DAY" | "VEN-VJ";
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type InternationalizedArrayReference = Array<{
  _key: string;
} & InternationalizedArrayReferenceValue>;

export type AllSanitySchemaTypes = SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityFileAsset | Geopoint | NavigationItem | Trainer | Role | Member | Partner | Configuration | InternationalizedArrayStringValue | InternationalizedArrayString | TranslationMetadata | InternationalizedArrayReferenceValue | Vacancy | Page | Event | Programme | Post | Person | SanityImageCrop | SanityImageHotspot | SanityImageAsset | SanityAssetSourceData | SanityImageMetadata | Slug | InternationalizedArrayReference;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "configuration" && language == $language][0] {    ...,    navigation[] {      title,      linkType,      page-> {        slug,        type      },      customUrl,      children[] {        title,        linkType,        page-> {          slug,          type        },        customUrl,        children[] {          title,          linkType,          page-> {            slug,            type          },          customUrl,          children[] {            title,            linkType,            page-> {              slug,              type            },            customUrl          }        }      }    }  }
export type SettingsQueryResult = {
  _id: string;
  _type: "configuration";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  navigation: Array<{
    title: string | null;
    linkType: "custom" | "events" | "page" | "posts" | "submenu" | "trainers" | "vacancies" | null;
    page: {
      slug: Slug | null;
      type: "members" | "other" | "partners" | "people" | "programmes" | null;
    } | null;
    customUrl: string | null;
    children: Array<{
      title: string | null;
      linkType: "custom" | "events" | "page" | "posts" | "submenu" | "trainers" | "vacancies" | null;
      page: {
        slug: Slug | null;
        type: "members" | "other" | "partners" | "people" | "programmes" | null;
      } | null;
      customUrl: string | null;
      children: Array<{
        title: string | null;
        linkType: "custom" | "events" | "page" | "posts" | "submenu" | "trainers" | "vacancies" | null;
        page: {
          slug: Slug | null;
          type: "members" | "other" | "partners" | "people" | "programmes" | null;
        } | null;
        customUrl: string | null;
        children: Array<{
          title: string | null;
          linkType: "custom" | "events" | "page" | "posts" | "submenu" | "trainers" | "vacancies" | null;
          page: {
            slug: Slug | null;
            type: "members" | "other" | "partners" | "people" | "programmes" | null;
          } | null;
          customUrl: string | null;
        }> | null;
      }> | null;
    }> | null;
  }> | null;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    metadataBase?: string;
    _type: "image";
  };
} | null;
// Variable: featuredPostsQuery
// Query: *[_type == "post" && defined(slug.current) && language == $language] | order(date desc, _updatedAt desc) [0...$quantity] {    content,      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  image,  "date": coalesce(date, _updatedAt),  "author": author->{"name": coalesce(name, "Anonymous"), picture},  }
export type FeaturedPostsQueryResult = Array<{
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  _id: string;
  status: "draft" | "published";
  title: string | "Untitled";
  slug: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  date: string;
  author: {
    name: string | "Anonymous";
    picture: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
}>;
// Variable: moreStoriesQuery
// Query: *[_type == "post" && _id != $skip && defined(slug.current) && language == $language] | order(date desc, _updatedAt desc) [0...$limit] {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  image,  "date": coalesce(date, _updatedAt),  "author": author->{"name": coalesce(name, "Anonymous"), picture},  }
export type MoreStoriesQueryResult = Array<{
  _id: string;
  status: "draft" | "published";
  title: string | "Untitled";
  slug: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  date: string;
  author: {
    name: string | "Anonymous";
    picture: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
}>;
// Variable: postQuery
// Query: *[_type == "post" && slug.current == $slug && language == $language] [0] {    content,      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  image,  "date": coalesce(date, _updatedAt),  "author": author->{"name": coalesce(name, "Anonymous"), picture},  }
export type PostQueryResult = {
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  _id: string;
  status: "draft" | "published";
  title: string | "Untitled";
  slug: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  date: string;
  author: {
    name: string | "Anonymous";
    picture: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
} | null;
// Variable: pageQuery
// Query: *[_type == "page" && slug.current == $slug && language == $language] [0] {    _id,    content,    "title": coalesce(title, "Untitled"),    "slug": slug.current,  }
export type PageQueryResult = {
  _id: string;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  title: string | "Untitled";
  slug: string | null;
} | null;
// Variable: pageTypeQuery
// Query: *[_type == "page" && type == $type && language == $language] [0] {    _id,    content,    "title": coalesce(title, "Untitled"),  }
export type PageTypeQueryResult = {
  _id: string;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  title: string | "Untitled";
} | null;
// Variable: partnersQuery
// Query: *[_type == "partner"] {    _id,    "title": coalesce(title, "Untitled"),    "logo": logo.asset->url,    description  }
export type PartnersQueryResult = Array<{
  _id: string;
  title: string | "Untitled";
  logo: string | null;
  description: Array<{
    _key: string;
  } & InternationalizedArrayStringValue> | null;
}>;
// Variable: programmesQuery
// Query: *[_type == "programme"] {    _id,    email,    "title": coalesce(title, "Untitled"),    description,    "managers": managers[]->{      _id,      "name": coalesce(name, "Untitled"),      "picture": picture.asset->url    }  }
export type ProgrammesQueryResult = Array<{
  _id: string;
  email: string | null;
  title: string | "Untitled";
  description: InternationalizedArrayString | null;
  managers: Array<{
    _id: string;
    name: string | "Untitled";
    picture: string | null;
  }> | null;
}>;
// Variable: peopleQuery
// Query: *[_type == "role" && dateTime($date) >= dateTime(start + 'T00:00:00Z') && (dateTime($date) < dateTime(end + 'T00:00:00Z') || !defined(end))] {      _id,  type,  email,  title,  bureauRole,  officeRole,  organization,  "name": person->name,  "picture": person->picture.asset->url  }
export type PeopleQueryResult = Array<{
  _id: string;
  type: "advisory-council" | "bureau-member" | "honorary-member" | "individual-member" | "office" | "ombudsperson" | "regional-representative" | null;
  email: string | null;
  title: string | null;
  bureauRole: "president" | "secretary-general" | "treasurer" | "vice-president" | null;
  officeRole: "executive-director" | "intern" | "project-manager" | null;
  organization: "ALYF" | "CALD" | "JULAC" | "LYMEC" | null;
  name: string | null;
  picture: string | null;
}>;
// Variable: eventsQuery
// Query: *[_type == "event" && language == $language] | order(start desc) {    _id,    "title": coalesce(title, "Untitled"),    "slug": slug.current,    type,    location,    start,    end,    "image": image.asset->url,    description,    "contactPerson": {      "person": contactPerson.person->{        _id,        "name": coalesce(name, "Untitled"),        "picture": picture.asset->url      },      "email": contactPerson.email    },    "trainers": trainers[]->{      _id,      email,      expertises,      languages,      "person": person->{        _id,        "name": coalesce(name, "Untitled"),        "picture": picture.asset->url,        biography      }    }  }
export type EventsQueryResult = Array<{
  _id: string;
  title: string | "Untitled";
  slug: string | null;
  type: "ga" | "seminar" | "workshop" | null;
  location: string | null;
  start: string | null;
  end: string | null;
  image: string | null;
  description: InternationalizedArrayString | null;
  contactPerson: {
    person: {
      _id: string;
      name: string | "Untitled";
      picture: string | null;
    } | null;
    email: string | null;
  };
  trainers: Array<{
    _id: string;
    email: string | null;
    expertises: Array<string> | null;
    languages: Array<"ar" | "de" | "en" | "es" | "fr" | "it" | "ja" | "nl" | "pt" | "ru" | "zh"> | null;
    person: {
      _id: string;
      name: string | "Untitled";
      picture: string | null;
      biography: InternationalizedArrayString | null;
    } | null;
  }> | null;
}>;
// Variable: vacanciesQuery
// Query: *[_type == "vacancy" && language == $language] | order(deadline asc) {    _id,    "title": coalesce(title, "Untitled"),    description,    location,    applicationUrl,    deadline  }
export type VacanciesQueryResult = Array<{
  _id: string;
  title: string | "Untitled";
  description: InternationalizedArrayString | null;
  location: string | null;
  applicationUrl: string | null;
  deadline: string | null;
}>;
// Variable: trainersQuery
// Query: *[_type == "trainer"] {    _id,    email,    expertises,    languages,    "person": person->{      _id,      "name": coalesce(name, "Untitled"),      picture,      biography    }  }
export type TrainersQueryResult = Array<{
  _id: string;
  email: string | null;
  expertises: Array<string> | null;
  languages: Array<"ar" | "de" | "en" | "es" | "fr" | "it" | "ja" | "nl" | "pt" | "ru" | "zh"> | null;
  person: {
    _id: string;
    name: string | "Untitled";
    picture: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    biography: InternationalizedArrayString | null;
  } | null;
}>;
// Variable: membersQuery
// Query: *[_type == "member"] {    _id,    memberId,    name,    "logo": logo.asset->url,    website,    wiki,    fb,    twitter,    ig  }
export type MembersQueryResult = Array<{
  _id: string;
  memberId: "ALYF" | "AND-JLA" | "ARG-GJFL" | "ARM-ANC" | "AUT-JUNOS" | "AZE-PH" | "BAS-EGI" | "BEL-FEL" | "BEL-JVLD" | "BFA-FL" | "BFA-RNJL" | "BGR-YMRF" | "BIH-YFNS" | "BLR-CF" | "BLR-YB" | "BOL-NMJ" | "CALD" | "CAN-YLC" | "CAT-JNC" | "CHE-JS" | "CHL-JE" | "CIV-JALIDE" | "CIV-JELIC" | "CIV-OJLCI" | "CIV-RHDP" | "COD-JEPR" | "COG-CLE" | "DEU-JULIS" | "DEU-LHG" | "DNK-LAU" | "DNK-RU" | "DNK-VU" | "EGY-EL" | "EGY-EYC" | "EST-NE2" | "FIN-FCY" | "FIN-SU" | "FRA-JR" | "GBR-YL" | "GEO-FK" | "GEO-IIL" | "GHA-PYM" | "GHA-YLG" | "GIB-GLY" | "GIN-CNJR" | "GIN-OJLG" | "GRC-NEON" | "HRV-IDY" | "HRV-MHNS" | "HUN-MT" | "IRQ-SASA" | "IRQ-VIO" | "ISR-YYA" | "JOR-FTF" | "JOR-S42" | "JULAC" | "KEN-ODM" | "LBN-FY" | "LTU-LLJ" | "LVA-PARJ" | "LYMEC" | "MAR-AJA" | "MAR-CDC" | "MAR-HRK" | "MKD-LDM" | "MNE-YLM" | "MRT-FCA" | "NIC-AVZ" | "NLD-JD" | "NLD-JOVD" | "NOR-NLS" | "NOR-NUV" | "NPL-YI" | "PER-IPL" | "POL-NY" | "PRY-JLRA" | "ROU-USRT" | "RUS-YDMV" | "SDN-FYSO" | "SEN-CEEP" | "SEN-COJER" | "SEN-FJR" | "SEN-JLD" | "SEN-JLS" | "SEN-MFA" | "SEN-PCR" | "SEN-RM" | "SVK-YP" | "SWE-CUF" | "SWE-LUF" | "SYR-AYLS" | "TUR-3HM" | "TZA-ACTW" | "TZA-PYI" | "UKR-EYU" | "UKR-LDLU" | "USA-YDA" | "VEN-VJ" | "ZAF-DAY" | null;
  name: null;
  logo: string | null;
  website: string | null;
  wiki: string | null;
  fb: string | null;
  twitter: string | null;
  ig: string | null;
}>;

// Source: ./src/app/(content)/[locale]/pages/[slug]/page.tsx
// Variable: pageSlugs
// Query: *[_type == "page" && defined(slug.current)]{"slug": slug.current}
export type PageSlugsResult = Array<{
  slug: string | null;
}>;

// Source: ./src/app/(content)/[locale]/posts/[slug]/page.tsx
// Variable: postSlugs
// Query: *[_type == "post" && defined(slug.current)]{"slug": slug.current}
export type PostSlugsResult = Array<{
  slug: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"configuration\" && language == $language][0] {\n    ...,\n    navigation[] {\n      title,\n      linkType,\n      page-> {\n        slug,\n        type\n      },\n      customUrl,\n      children[] {\n        title,\n        linkType,\n        page-> {\n          slug,\n          type\n        },\n        customUrl,\n        children[] {\n          title,\n          linkType,\n          page-> {\n            slug,\n            type\n          },\n          customUrl,\n          children[] {\n            title,\n            linkType,\n            page-> {\n              slug,\n              type\n            },\n            customUrl\n          }\n        }\n      }\n    }\n  }\n": SettingsQueryResult;
    "\n  *[_type == \"post\" && defined(slug.current) && language == $language] | order(date desc, _updatedAt desc) [0...$quantity] {\n    content,\n    \n  _id,\n  \"status\": select(_originalId in path(\"drafts.**\") => \"draft\", \"published\"),\n  \"title\": coalesce(title, \"Untitled\"),\n  \"slug\": slug.current,\n  image,\n  \"date\": coalesce(date, _updatedAt),\n  \"author\": author->{\"name\": coalesce(name, \"Anonymous\"), picture},\n\n  }\n": FeaturedPostsQueryResult;
    "\n  *[_type == \"post\" && _id != $skip && defined(slug.current) && language == $language] | order(date desc, _updatedAt desc) [0...$limit] {\n    \n  _id,\n  \"status\": select(_originalId in path(\"drafts.**\") => \"draft\", \"published\"),\n  \"title\": coalesce(title, \"Untitled\"),\n  \"slug\": slug.current,\n  image,\n  \"date\": coalesce(date, _updatedAt),\n  \"author\": author->{\"name\": coalesce(name, \"Anonymous\"), picture},\n\n  }\n": MoreStoriesQueryResult;
    "\n  *[_type == \"post\" && slug.current == $slug && language == $language] [0] {\n    content,\n    \n  _id,\n  \"status\": select(_originalId in path(\"drafts.**\") => \"draft\", \"published\"),\n  \"title\": coalesce(title, \"Untitled\"),\n  \"slug\": slug.current,\n  image,\n  \"date\": coalesce(date, _updatedAt),\n  \"author\": author->{\"name\": coalesce(name, \"Anonymous\"), picture},\n\n  }\n": PostQueryResult;
    "\n  *[_type == \"page\" && slug.current == $slug && language == $language] [0] {\n    _id,\n    content,\n    \"title\": coalesce(title, \"Untitled\"),\n    \"slug\": slug.current,\n  }\n": PageQueryResult;
    "\n  *[_type == \"page\" && type == $type && language == $language] [0] {\n    _id,\n    content,\n    \"title\": coalesce(title, \"Untitled\"),\n  }\n": PageTypeQueryResult;
    "\n  *[_type == \"partner\"] {\n    _id,\n    \"title\": coalesce(title, \"Untitled\"),\n    \"logo\": logo.asset->url,\n    description\n  }\n": PartnersQueryResult;
    "\n  *[_type == \"programme\"] {\n    _id,\n    email,\n    \"title\": coalesce(title, \"Untitled\"),\n    description,\n    \"managers\": managers[]->{\n      _id,\n      \"name\": coalesce(name, \"Untitled\"),\n      \"picture\": picture.asset->url\n    }\n  }\n": ProgrammesQueryResult;
    "\n  *[_type == \"role\" && dateTime($date) >= dateTime(start + 'T00:00:00Z') && (dateTime($date) < dateTime(end + 'T00:00:00Z') || !defined(end))] {\n    \n  _id,\n  type,\n  email,\n  title,\n  bureauRole,\n  officeRole,\n  organization,\n  \"name\": person->name,\n  \"picture\": person->picture.asset->url\n\n  }\n": PeopleQueryResult;
    "\n  *[_type == \"event\" && language == $language] | order(start desc) {\n    _id,\n    \"title\": coalesce(title, \"Untitled\"),\n    \"slug\": slug.current,\n    type,\n    location,\n    start,\n    end,\n    \"image\": image.asset->url,\n    description,\n    \"contactPerson\": {\n      \"person\": contactPerson.person->{\n        _id,\n        \"name\": coalesce(name, \"Untitled\"),\n        \"picture\": picture.asset->url\n      },\n      \"email\": contactPerson.email\n    },\n    \"trainers\": trainers[]->{\n      _id,\n      email,\n      expertises,\n      languages,\n      \"person\": person->{\n        _id,\n        \"name\": coalesce(name, \"Untitled\"),\n        \"picture\": picture.asset->url,\n        biography\n      }\n    }\n  }\n": EventsQueryResult;
    "\n  *[_type == \"vacancy\" && language == $language] | order(deadline asc) {\n    _id,\n    \"title\": coalesce(title, \"Untitled\"),\n    description,\n    location,\n    applicationUrl,\n    deadline\n  }\n": VacanciesQueryResult;
    "\n  *[_type == \"trainer\"] {\n    _id,\n    email,\n    expertises,\n    languages,\n    \"person\": person->{\n      _id,\n      \"name\": coalesce(name, \"Untitled\"),\n      picture,\n      biography\n    }\n  }\n": TrainersQueryResult;
    "\n  *[_type == \"member\"] {\n    _id,\n    memberId,\n    name,\n    \"logo\": logo.asset->url,\n    website,\n    wiki,\n    fb,\n    twitter,\n    ig\n  }\n": MembersQueryResult;
    "*[_type == \"page\" && defined(slug.current)]{\"slug\": slug.current}": PageSlugsResult;
    "*[_type == \"post\" && defined(slug.current)]{\"slug\": slug.current}": PostSlugsResult;
  }
}
